sudo:
  - false

language:
  - cpp

addons:
  apt:
    sources:
      - ppa:ubuntu-toolchain-r/test
    packages:
      - g++-4.8

compiler:
  - gcc

script:
  - which g++-4.8
  - g++-4.8 --version
  - g++-4.8 -std=c++11 test.cpp -o prog && ./prog
