sudo:
  - false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8-multilib
      - libstdc++-4.8-dev

compiler:
  - gcc

script:
  - which g++-4.8
  - g++-4.8 --version
  - g++-4.8 -std=c++11 -m32 test.cpp -o prog && ./prog
